-- =====================================================================
--  CollabDocs  -  PostgreSQL schema  (PostgreSQL 14+)
--  Applied automatically by Flyway on backend start-up.
-- =====================================================================

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE users (
    username       VARCHAR(30)  PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    password       VARCHAR(100) NOT NULL,                 -- BCrypt hash, never plain text
    role           VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at  TIMESTAMPTZ,

    CONSTRAINT ck_users_username CHECK (username ~ '^[A-Za-z0-9_.-]{3,30}$'),
    CONSTRAINT ck_users_role     CHECK (role IN ('USER', 'ADMIN'))
);

-- e-mail and username are unique regardless of letter case ("Alice" == "alice")
CREATE UNIQUE INDEX ux_users_email_lower    ON users (lower(email));
CREATE UNIQUE INDEX ux_users_username_lower ON users (lower(username));

-- ---------------------------------------------------------------------
-- documents
--   content = compact binary snapshot of the CRDT (see Crdt.java)
--   preview = first characters of the text, shown on dashboard cards
-- ---------------------------------------------------------------------
CREATE TABLE documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_username  VARCHAR(30)  NOT NULL
                    REFERENCES users (username) ON DELETE CASCADE ON UPDATE CASCADE,
    title           VARCHAR(255) NOT NULL,
    content         BYTEA        NOT NULL DEFAULT ''::bytea,
    preview         VARCHAR(300) NOT NULL DEFAULT '',
    char_count      INTEGER      NOT NULL DEFAULT 0,
    general_access  VARCHAR(20)  NOT NULL DEFAULT 'PRIVATE',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_documents_title  CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_documents_access CHECK (general_access IN ('PRIVATE', 'ANYONE_VIEW', 'ANYONE_EDIT')),
    CONSTRAINT ck_documents_chars  CHECK (char_count >= 0)
);

-- dashboard query: "my documents, most recently edited first"
CREATE INDEX ix_documents_owner_updated ON documents (owner_username, updated_at DESC);

-- ---------------------------------------------------------------------
-- document_collaborators   (who a document is shared with)
--   The owner is NOT stored here; ownership lives in documents.owner_username.
-- ---------------------------------------------------------------------
CREATE TABLE document_collaborators (
    doc_id      BIGINT      NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    username    VARCHAR(30) NOT NULL REFERENCES users (username) ON DELETE CASCADE ON UPDATE CASCADE,
    permission  VARCHAR(10) NOT NULL DEFAULT 'VIEW',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (doc_id, username),
    CONSTRAINT ck_collab_permission CHECK (permission IN ('VIEW', 'EDIT'))
);

-- dashboard query: "documents shared with me"
CREATE INDEX ix_collaborators_username ON document_collaborators (username);

-- ---------------------------------------------------------------------
-- keep documents.updated_at correct even for manual / bulk SQL updates
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_documents_updated_at
    BEFORE UPDATE ON documents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
